language: c

before_install:
 - /sbin/start-stop-daemon --start
        --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background
        --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

install:
 - sudo apt-get update
 - sudo apt-get install
        expect
        gstreamer0.10-plugins-bad
        gstreamer0.10-plugins-base
        gstreamer0.10-plugins-good
        gstreamer0.10-tools
        gstreamer0.10-x
        moreutils
        pep8
        pylint
        python-docutils
        python-flask
        python-gobject
        python-jinja2
        python-nose
        python-numpy
        python-opencv
        tesseract-ocr
 - sudo pip install selenium
 - git clone http://git.chromium.org/webm/webminspector.git ~/webminspector
 - make prefix=$HOME install

script:
 - PATH=~/bin:~/webminspector:$PATH DISPLAY=:99.0 make check
